controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_user_profile:
    path: /api/users/{id}
    controller: App\Controller\UserController::getUserProfile
    
follow_followers:
    path: /api/follows/{userId}/followers
    controller: App\Controller\FollowController::followers
    methods: [GET]